version: '3.8'

services:
  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=123456
      - POSTGRESQL_PASSWORD=root 
      - POSTGRESQL_DATABASE=projeto_faculdade_bd
        